// All of system managers cmds

#ifndef SATCOMM_CMD_H
#define SATCOMM_CMD_H

// Aliased to preserve backward compatibility
#define SATCOMM_1ST_INHIBIT_CMD 32
#define SATCOMM_1ST_INHIBIT_RESP (SATCOMM_1ST_INHIBIT_CMD | 0x80)
#define SATCOMM_UNSQUELCH_CMD SATCOMM_1ST_INHIBIT_CMD
#define SATCOMM_UNSQUELCH_RESP SATCOMM_1ST_INHIBIT_RESP

#define SATCOMM_SUPPRESS_RF_CMD 33
#define SATCOMM_SUPPRESS_RF_RESP (SATCOMM_SUPPRESS_RF_CMD | 0x80)
#define SATCOMM_RESUME_RF_CMD 34
#define SATCOMM_RESUME_RF_RESP (SATCOMM_RESUME_RF_CMD | 0x80)
#define SATCOMM_SET_DIGIPEATS_CMD 35
#define SATCOMM_SET_DIGIPEATS_RESP (SATCOMM_SET_DIGIPEATS_CMD | 0x80)
#define SATCOMM_FORCE_LOCAL_RF_PARAMS_CMD 36
#define SATCOMM_FORCE_LOCAL_RF_PARAMS_RESP (SATCOMM_FORCE_LOCAL_RF_PARAMS_CMD | 0x80)
#define SATCOMM_NEGOTIATE_RF_PARAMS_CMD 37
#define SATCOMM_NEGOTIATE_RF_PARAMS_RESP (SATCOMM_NEGOTIATE_RF_PARAMS_CMD | 0x80)
#define SATCOMM_CW_OFF_CMD 38
#define SATCOMM_CW_OFF_CMD_RESP (SATCOMM_CW_OFF_CMD | 0x80)
#define SATCOMM_CW_SHORT_CMD 39
#define SATCOMM_CW_SHORT_CMD_RESP (SATCOMM_CW_SHORT_CMD | 0x80)
#define SATCOMM_CW_LONG_CMD 40
#define SATCOMM_CW_LONG_CMD_RESP (SATCOMM_CW_LONG_CMD | 0x80)
#define SATCOMM_RF_DEBUG 41
#define SATCOMM_RF_RESP (SATCOMM_CW_LONG_CMD | 0x80)

#define SATCOMM_2ND_INHIBIT_CMD 42
#define SATCOMM_2ND_INHIBIT_RESP (SATCOMM_2ND_INHIBIT_CMD | 0x80)
#define SATCOMM_FORCE_UNSQUELCH_CMD 43
#define SATCOMM_FORCE_UNSQUELCH_RESP (SATCOMM_FORCE_UNSQUELCH_CMD | 0x80)

#define SATCOMM_FAKE_TELEM_ON_CMD 44
#define SATCOMM_FAKE_TELEM_ON_RESP (SATCOMM_FAKE_TELEM_ON_CMD | 0x80)
#define SATCOMM_FAKE_TELEM_OFF_CMD 45
#define SATCOMM_FAKE_TELEM_OFF_RESP (SATCOMM_FAKE_TELEM_OFF_CMD | 0x80)

#define SATCOMM_CMD_PARAM_UNKNOWN 0
#define SATCOMM_CMD_PARAM_GFSK 1
#define SATCOMM_CMD_PARAM_FSK 2
#define SATCOMM_CMD_PARAM_MSK 3
#define SATCOMM_CMD_PARAM_GMSK 4
#define SATCOMM_CMD_PARAM_ASK 5
#define SATCOMM_CMD_PARAM_OQPSK 6
#define SATCOMM_CMD_PARAM_NRZ 7
#define SATCOMM_CMD_PARAM_NRZ_SCRAMBLED 8
#define SATCOMM_CMD_PARAM_NRZI 9
#define SATCOMM_CMD_PARAM_NRZI_SCRAMBLED 10
#define SATCOMM_CMD_PARAM_FM1 11
#define SATCOMM_CMD_PARAM_FM0 12
#define SATCOMM_CMD_PARAM_MANCHESTER 13
#define SATCOMM_CMD_PARAM_FEC_ON 13
#define SATCOMM_CMD_PARAM_FEC_OFF 14
#define SATCOMM_CMD_PARAM_CRC_CCITT 15
#define SATCOMM_CMD_PARAM_CRC_16 16
#define SATCOMM_CMD_PARAM_CRC_32 17
#define SATCOMM_CMD_PARAM_NO_CHANGE 255

#define SATCOMM_UHF_ACTIVE_EVENT 1
#define SATCOMM_UHF_IDLE_EVENT 2

struct SATCOMM_RF_Params {
   uint32_t freq;
   uint32_t bitrate;
   uint8_t modulation;
   uint8_t encoding;
   uint8_t crc;
   uint8_t fec;
   uint32_t duration;
   uint16_t giveup;
   uint16_t intf_id;
   uint16_t q_id;
   uint16_t rem_intf_id;
   uint16_t rem_q_id;
} __attribute((packed));

#define SATCOMM_1ST_INHIBIT_OFF_EVT 1
#define SATCOMM_2ND_INHIBIT_OFF_EVT 2
#define SATCOMM_UNSQUELCH_EVT 3

#endif
