// All of system managers cmds

#ifndef SYS_MANAGER_CMD_H
#define SYS_MANAGER_CMD_H

#define SYS_MANAGER_STATUS 1
#define SYS_REBOOT 3
#define TOGGLE_REG 4
#define KILL_PROC 5
#define ADD_CERT 6 // Not tested
#define TEMP_STATUS 7
#define TEMP_STATUS_RESP 8
#define POWER_STATUS 9
#define POWER_STATUS_RESP 10
#define ALL_TELEMETRY 11
#define ALL_TELEMETRY_RESP 12
#define STANDARD_TELEM 13
#define STANDARD_TELEM_RESP 14
#define GET_CP9_DATA 15
#define GET_CP9_DATA_RESP 16
#define SYSTEM_TELEM 17
#define SYSTEM_TELEM_RESP 18
#define ANT_TIMER_ON_CMD 19
#define ANT_TIMER_OFF_CMD 20
#define ANT_DEPLOY_NOW_CMD 21
#define ANT_PERSISTENT_RESET_CMD 22
#define RESET_COUNTER_CMD 23
#define DAILY_ANT_TIMER_OFF_CMD 24
#define SOC_SIMULATION_PERCENT_CMD 25
#define SOC_SIMULATION_PERCENT_RESP 26
#define SOC_SIMULATION_OFF_CMD 27
#define SOC_SIMULATION_OFF_RESP 28
#define BATT_CTRL_CMD 29
#define BATT_CTRL_RESP 30
#define SYS_SET_DEPLOYABLE_STATE 31
#define SYS_SET_DEPLOYABLE_STATE_RESP 32
#define SYS_CLEAR_DEPLOYABLE_STATE 33
#define SYS_CLEAR_DEPLOYABLE_STATE_RESP 34
#define BATT_OV_RECOVERY_ON 35
#define BATT_OV_RECOVERY_ON_RESP 36
#define BATT_OV_RECOVERY_OFF 37
#define BATT_OV_RECOVERY_OFF_RESP 38
#define GPS_STATUS 39
#define GPS_STATUS_RESP 40
#define GPS_TIME 41
#define GPS_TIME_RESP 42

#endif
