// All of beacons cmds

#ifndef BEACON_CMD_H
#define BEACON_CMD_H

#define BEACON_STATUS 1
#define BEACON_STATUS_RESP 241

#define BEACON_SET_IDLE_RATE 3
#define BEACON_SET_IDLE_RATE_RESP (BEACON_SET_IDLE_RATE | 0x80)

#define BEACON_SET_IDLE_RATE_PERSIST 4
#define BEACON_SET_IDLE_RATE_PERSIST_RESP (BEACON_SET_IDLE_RATE_PERSIST | 0x80)

#define BEACON_SET_ACTIVE_RATE 5
#define BEACON_SET_ACTIVE_RATE_RESP (BEACON_SET_ACTIVE_RATE | 0x80)

#define BEACON_SET_ACTIVE_RATE_PERSIST 6
#define BEACON_SET_ACTIVE_RATE_PERSIST_RESP (BEACON_SET_ACTIVE_RATE_PERSIST | 0x80)

#define BEACON_SET_RATES 7
#define BEACON_SET_RATES_RESP (BEACON_SET_RATES | 0x80)

#define BEACON_SET_RATES_PERSIST 8
#define BEACON_SET_RATES_PERSIST_RESP (BEACON_SET_RATES_PERSIST | 0x80)

#define BEACON_UHF_ACTIVE_TEST 9
#define BEACON_UHF_ACTIVE_TEST_RESP (BEACON_UHF_ACTIVE_TEST | 0x80)

#define BEACON_UHF_IDLE_TEST 10
#define BEACON_UHF_IDLE_TEST_RESP (BEACON_UHF_IDLE_TEST | 0x80)

#endif
